import type { LogicState } from './types';
import { buildItemsMap } from './itemMapping';

// ER tracker: entrance name → destination area name (from yEntrances)
// We need to convert from "OoT X to OoT Y" names → region names
// This mapping will be filled in once we have the world graph loaded
export function buildLogicState(
  yItemsSnapshot: Map<string, number>,
  ySettingsSnapshot: Map<string, any>,
  yEntrancesSnapshot: Map<string, string>,
  enabledTricks: Set<string> = new Set(),
): LogicState {
  const items = buildItemsMap(yItemsSnapshot);

  // Settings: flatten the Yjs settings map
  const settings = new Map<string, string | boolean | number>();
  for (const [k, v] of ySettingsSnapshot) {
    settings.set(k, v);
  }

  // ER overrides: map entrance ID → destination region name
  // yEntrances stores: entranceId → destination entrance name (full OoTMM name)
  // The engine will resolve these against the world graph
  const erOverrides = new Map<string, string>();
  for (const [entranceId, destName] of yEntrancesSnapshot) {
    erOverrides.set(entranceId, destName);
  }

  // Seed consumable events from owned items.
  // In OoTMM, ammo events (ARROWS, BOMBS, SEEDS…) are normally generated by shops/drops
  // reached during BFS. If the player has the launcher, assume they have ammo.
  const events = new Set<string>();
  if ((items.get('BOW') ?? 0) > 0 || (items.get('SHARED_BOW') ?? 0) > 0) {
    events.add('ARROWS'); events.add('MM_ARROWS');
  }
  if ((items.get('BOMB_BAG') ?? 0) > 0 || (items.get('SHARED_BOMB_BAG') ?? 0) > 0) {
    events.add('BOMBS'); events.add('BOMBS_OR_BOMBCHU'); events.add('MM_BOMBS'); events.add('MM_BOMBS_OR_BOMBCHU');
  }
  if ((items.get('SLINGSHOT') ?? 0) > 0) events.add('SEEDS');
  if ((items.get('STICKS') ?? 0) > 0 || (items.get('STICKS_10') ?? 0) > 0) {
    events.add('STICKS'); events.add('MM_STICKS');
  }
  if ((items.get('NUTS') ?? 0) > 0 || (items.get('NUTS_10') ?? 0) > 0) {
    events.add('NUTS'); events.add('MM_NUTS');
  }
  if ((items.get('MAGIC_UPGRADE') ?? 0) > 0 || (items.get('SHARED_MAGIC_UPGRADE') ?? 0) > 0) {
    events.add('MAGIC'); events.add('MM_MAGIC');
  }

  return {
    items,
    age: 'child', // placeholder — engine overrides this via stateForAge()
    events,
    settings,
    erOverrides,
    tricks: enabledTricks,
    flags: new Set(),
  };
}
